### PR TITLE
Removed += and add ''.join() to improve performance

### PR DESCRIPTION
**Pull request by Kiloreux**
#51 I removed += in log_msg and exchanged it with ''.join()

### CODE REVIEW

**Comment by T045T** [comment]
Thanks for the contribution! However, it seems like `+=` might actually be faster than `join()` nowadays:
http://jsperf.com/array-join-vs-string-connect
http://jsperf.com/join-concat/2

**Comment by pttp** [comment]
python: https://wiki.python.org/moin/PythonSpeed/PerformanceTips#String_Concatenation

**Comment by T045T** [comment]
Sorry, I thought this PR was for one of the JavaScript repos, my bad.

After reading that Wiki page, it seems like the patch still contains way more `join()` calls than necessary though.
Shouldn't it only be called when assembling the final string, rather than calling it when adding each part?
Intuitively, the patched version should yield similar performance, since the string is still replaced for each addition.

**Comment by ablakey** [comment]
That would also result in cleaner code. Collect a list of string elements then join them all at the end.

**Comment by Kiloreux** [comment]
@T045T is it okay if i put them in a list and join them by the end ? and squash the 2 commits together ?

**Comment by T045T** [comment]
Sounds good :+1: 
As long as the PR isn't merged, you can squash commits however you like :)

**Pull request closed without merging**
