### PR TITLE
Fixed utf-8 decode exception when in bson_only_mode

### PR DESCRIPTION
**Pull request by JKaniarz**
**Public API Changes**

None

**Description**

Modifed Protocol.incoming to:

- accept both bytes() and str (and removed the utf-8 decode from RosbridgeWebSocket.on_message()).
- Deinterleved the BSON handling code from the JSON handling code.
- Buffer bytes() in partial BSON messages.

This is also a steppingstone toward getting TCP working again.

https://github.com/RobotWebTools/rosbridge_suite/issues/718

### CODE REVIEW

**Comment by JKaniarz** [comment]
Is there anything standing in the way of merging this?

**Comment by jtbandes** [comment]
Is there a way we can add tests for this fix? Or is that impossible now that we have only the websocket server?

**Comment by JKaniarz** [comment]
I'm not familiar with your testing framework but here's what the tests would need to be for RosbridgeWebSocket:

- Send a time message in BSON format with all zero variables and make sure that it is sent to Protocol as bytes(). The trick with this message is that these BSON bytes can successfully decode as UTF-8 and we want to make sure that it isn't converted.
- Send a >127 byte BSON message over the wire (PoseWithCovarience will work) and make sure that it is sent to Protocol as bytes() and no exception is thrown. This message can't be converted to UTF-8 and we want to make sure it isn't silently dropped.

These tests would apply to the TCP and UDP connections too if you ever bring them back.

**Comment by JKaniarz** [comment]
Side conversation about Protocol's buffering. I left the buffering as-is, but it's only necessary for JSON over TCP. WebSocket and UDP will naturally provide JSON and BSON at the correct length. BSON has length bytes, so it's easy to chop up the TCP stream (which is what the old TCP handler did, I copied it into Protocol).

Would you like me to trim it down? As it stands, any future protocols can just blast bytes at Protocol and Protocol will do the slicing.

**Comment by JKaniarz** [comment]
Is there any interest in this?

**Pull request closed without merging**
