### PR TITLE
BSON Encoding for Binary Objects

### PR DESCRIPTION
**Pull request by DLu**
Via #169 

Allows binary information to be transmitted as BSON objects when the binary_encoding flag is set to bson.

### CODE REVIEW

**Comment by rctoris** [comment]
Looks like the build is failing to find bson. Will have to add it as a rosdep in this case for release.

**Comment by rctoris** [comment]
@DLu any updates on adding `bson` as a dependency?

**Comment by DLu** [comment]
Waiting on https://github.com/ros/rosdistro/pull/8873

**Comment by DLu** [comment]
Should be good to go.

**Pull request merged**
