### PR TITLE
Miscellaneous fixes: flake8 --select=E402,E731,E741,F821

### PR DESCRIPTION
**Pull request by cclauss**
Fix six miscellaneous flake8 issues that formatters like [psf/black](https://github.com/psf/black) will not auto-fix.
```
2     E402 module level import not at top of file
1     E731 do not assign a lambda expression, use a def
1     E741 ambiguous variable name 'l'
2     F821 undefined name 'get_service_uri'
```

### CODE REVIEW

**Comment by amacneil** [comment]
Can you add all the fixed checks to `setup.cfg` in these PRs so we can prevent future regressions?

**Comment by cclauss** [comment]
Let's just land these PRs and run psf/black and we will pass ALL flake8 tests.

**Comment by cclauss** [comment]
Adding them is going to mean that each PR has conflicts with all others because they are all modifying the same line.

**Comment by amacneil** [comment]
> Adding them is going to mean that each PR has conflicts with all others because they are all modifying the same line.

I see, yes makes sense

**Review by jtbandes — APPROVED** [review]

**Pull request merged**
