### PR TITLE
Remove authentication, link to ROS 1 spec

### PR DESCRIPTION
**Pull request by amacneil**
**Public API Changes**
None

**Description**
- Authentication is not supported in ROS 2 rosbridge
- Add link to ros1 branch

### CODE REVIEW

**Review by jtbandes — APPROVED** [review]
Should we just ditch the numbering entirely?

**Comment by amacneil** [comment]
Probably. Or if the protocol is going to be versioned, then it should specify as much in the subprotocol?

**Comment by jtbandes** [comment]
I mostly meant the section numbering in the markdown.

**Comment by amacneil** [comment]
Oh, yeah could do. Maybe in a separate PR? If we did that the it would probably be best to addd a ToC.

I don't think the spec will evolve much tho? Will leave as is for now.

**Pull request merged**
