### PR TITLE
flake8 rosapi/scripts/rosapi_node

### PR DESCRIPTION
**Pull request by cclauss**
This is a Python file with no `.py` extension so `flake8` normally misses it.

I could not figure out three issues so I marked them with `# noqa: F821` but better solutions are always welcome.

# Before:
% `flake8 rosapi/scripts/rosapi_node`
```
rosapi/scripts/rosapi_node:41:1: F403 'from rosapi.srv import *' used; unable to detect undefined names
from rosapi.srv import *
^
rosapi/scripts/rosapi_node:42:1: F403 'from rosapi.msg import *' used; unable to detect undefined names
from rosapi.msg import *
^
rosapi/scripts/rosapi_node:65:29: F405 'Topics' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(Topics, '/rosapi/topics', self.get_topics)
                            ^
rosapi/scripts/rosapi_node:66:29: F405 'TopicsForType' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(TopicsForType, '/rosapi/topics_for_type', self.get_topics_for_type)
                            ^
rosapi/scripts/rosapi_node:67:29: F405 'TopicsAndRawTypes' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(TopicsAndRawTypes, '/rosapi/topics_and_raw_types', self.get_topics_and_raw_types)
                            ^
rosapi/scripts/rosapi_node:68:29: F405 'Services' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(Services, '/rosapi/services', self.get_services)
                            ^
rosapi/scripts/rosapi_node:69:29: F405 'ServicesForType' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(ServicesForType, '/rosapi/services_for_type', self.get_services_for_type)
                            ^
rosapi/scripts/rosapi_node:70:29: F405 'Nodes' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(Nodes, '/rosapi/nodes', self.get_nodes)
                            ^
rosapi/scripts/rosapi_node:71:29: F405 'NodeDetails' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(NodeDetails, '/rosapi/node_details', self.get_node_details)
                            ^
rosapi/scripts/rosapi_node:72:29: F405 'GetActionServers' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(GetActionServers, '/rosapi/action_servers', self.get_action_servers)
                            ^
rosapi/scripts/rosapi_node:73:29: F405 'TopicType' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(TopicType, '/rosapi/topic_type', self.get_topic_type)
                            ^
rosapi/scripts/rosapi_node:74:29: F405 'ServiceType' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(ServiceType, '/rosapi/service_type', self.get_service_type)
                            ^
rosapi/scripts/rosapi_node:75:29: F405 'Publishers' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(Publishers, '/rosapi/publishers', self.get_publishers)
                            ^
rosapi/scripts/rosapi_node:76:29: F405 'Subscribers' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(Subscribers, '/rosapi/subscribers', self.get_subscribers)
                            ^
rosapi/scripts/rosapi_node:77:29: F405 'ServiceProviders' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(ServiceProviders, '/rosapi/service_providers', self.get_service_providers)
                            ^
rosapi/scripts/rosapi_node:78:29: F405 'ServiceNode' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(ServiceNode, '/rosapi/service_node', self.get_service_node)
                            ^
rosapi/scripts/rosapi_node:79:29: F405 'MessageDetails' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(MessageDetails, '/rosapi/message_details', self.get_message_details)
                            ^
rosapi/scripts/rosapi_node:80:29: F405 'ServiceRequestDetails' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(ServiceRequestDetails, '/rosapi/service_request_details', self.get_service_request_details)
                            ^
rosapi/scripts/rosapi_node:81:29: F405 'ServiceResponseDetails' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(ServiceResponseDetails, '/rosapi/service_response_details', self.get_service_response_details)
                            ^
rosapi/scripts/rosapi_node:82:29: F405 'SetParam' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(SetParam, '/rosapi/set_param', self.set_param)
                            ^
rosapi/scripts/rosapi_node:83:29: F405 'GetParam' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(GetParam, '/rosapi/get_param', self.get_param)
                            ^
rosapi/scripts/rosapi_node:84:29: F405 'HasParam' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(HasParam, '/rosapi/has_param', self.has_param)
                            ^
rosapi/scripts/rosapi_node:85:29: F405 'DeleteParam' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(DeleteParam, '/rosapi/delete_param', self.delete_param)
                            ^
rosapi/scripts/rosapi_node:86:29: F405 'GetParamNames' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(GetParamNames, '/rosapi/get_param_names', self.get_param_names)
                            ^
rosapi/scripts/rosapi_node:87:29: F405 'GetTime' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
        self.create_service(GetTime, '/rosapi/get_time', self.get_time)
                            ^
rosapi/scripts/rosapi_node:248:12: F405 'ServiceHostResponse' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
    return ServiceHostResponse(proxy.get_service_host(request.service))
           ^
rosapi/scripts/rosapi_node:252:12: F405 'SearchParamResponse' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
    return SearchParamResponse(rosapi.params.search_param(request.name, rosapi.glob_helper.params))
           ^
rosapi/scripts/rosapi_node:252:32: F405 'rosapi' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
    return SearchParamResponse(rosapi.params.search_param(request.name, rosapi.glob_helper.params))
                               ^
rosapi/scripts/rosapi_node:252:73: F405 'rosapi' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
    return SearchParamResponse(rosapi.params.search_param(request.name, rosapi.glob_helper.params))
                                                                        ^
rosapi/scripts/rosapi_node:255:15: F405 'TypeDef' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
    typedef = TypeDef()
              ^
rosapi/scripts/rosapi_node:274:5: F405 'node' may be undefined, or defined from star imports: rosapi.msg, rosapi.srv
    node.destroy_node()
    ^
31
```

### CODE REVIEW

**Comment by amacneil** [comment]
How can we ensure flake8 catches this file in the future? Is there an option we can add to setup.cfg?

**Comment by cclauss** [comment]
The command `flake8 rosapi/scripts/rosapi_node .` should work.

**Comment by jtbandes** [comment]
Some of the other scripts in this repo use a .py file and, separately, a symlink which points at the .py file: https://github.com/RobotWebTools/rosbridge_suite/blob/ros2/rosbridge_server/scripts/rosbridge_websocket

Maybe we should use that approach here as well?

If we don't go with a symlink, a setup.cfg entry would be preferable to adding a step to the CI job, so that editor integration (e.g. VS Code's Python extension) can pick up the file as well.

**Comment by cclauss** [comment]
I would think that we want to do it as we do elsewhere in this repo.  If I do a symlink on my Mac and check that in, will git do the right thing or does git have some special syntax?

**Comment by amacneil** [comment]
For future reference: This is linting now due to pre-commit being better at finding files.

**Pull request closed without merging**
