### PR TITLE
Fix action cancellation by passing status from JSON (backport #953)

### PR DESCRIPTION
**Pull request by sea-bass**
Backports #953 to the `humble` branch.

### CODE REVIEW

**Comment by sea-bass** [comment]
I think the failing tests here may require some of the other backports to be in first.

**Review by MatthijsBurgh — APPROVED** [review]
Approval based on the diff being the same as the original PR. I only approve merging this PR, when the CI has been fixed (by merging other backports first).

**Comment by sea-bass** [comment]
> Approval based on the diff being the same as the original PR. I only approve merging this PR, when the CI has been fixed (by merging other backports first).

The other backports did not fix the failing test, but also

* The test has nothing do with this diff
* I built this branch locally on Rolling and it passes

I'm not sure why, but I've gone ahead and disabled the test. Let me know if this is okay.

**Comment by MatthijsBurgh** [comment]
It looks like we have flaky tests

**Comment by sea-bass** [comment]
> It looks like we have flaky tests

I'd call this something different than flaky if they consistently pass on Iron/Jazzy/Rolling, but seem to fail on Humble. But it's an issue nonetheless.

The only recent change that touched these files is https://github.com/RobotWebTools/rosbridge_suite/pull/958 (which was part of these backports), but it's also strange that the failures would then happen on this (unrelated) PR instead of the backport itself.

Let me try revert this change and see what CI thinks.

EDIT: Nope, reverting that PR did not help.

**Review by MatthijsBurgh — APPROVED** [review]

**Comment by sea-bass** [comment]
Mysteriously, I pulled down a ROS 2 Humble Docker container and tried to run the failing tests I skipped in there... and they passed.

**Pull request merged**
