### PR TITLE
Exapnding CBOR value extraction support

### PR DESCRIPTION
**Pull request by kedus42**
**Public API Changes**
None

**Description**
Changes allow CBOR value extraction to now also support messages with no __slot__ or _slot_types attributes.

### CODE REVIEW

**Comment by jtbandes** [comment]
Thanks for your contribution. Can you please provide some background explanation on this change? Why would any messages not have `__slots__` or `_slot_types`? Can you provide examples in the form of unit tests?

**Comment by mvollrath** [comment]
Looks like there is also a feature for rosapi providing ROS version in this PR, maybe an accident.

**Comment by amacneil** [comment]
@kedus42 can you please rebase this PR to remove the extra commits?

**Comment by defunctzombie** [comment]
Close since we've not heard back about this. If you are able to revisit we can take another look.

**Pull request closed without merging**
