### PR TITLE
Check if appropriate bson module is installed or not just after init_node (#198)

### PR DESCRIPTION
**Pull request by ledmonster**
Check whether mongodb oriented bson is installed or not just after init_node,
and if appropriate bson is not installed, shutdown node with error message.

See: https://github.com/RobotWebTools/rosbridge_suite/issues/198

### CODE REVIEW

**Comment by cjds** [comment]
This wrong BSON library thing tripped me up for quite a while.

**Comment by jihoonl** [comment]
ping

**Comment by jihoonl** [comment]
@ledmonster sorry I just realized that all reviews were in pending. Could you change the requested in review?

**Comment by jihoonl** [comment]
Looks good to me. thanks. merging it now.

**Pull request merged**
