### PR TITLE
Removes array delimiters while parsing parameters

### LINKED ISSUE #291: Service name matching is not working
I have a service in the root name space called `get_errors` and the ros_bridge_library fails to recognize the service unless I pre-pend a `/` to to the name in `services_glob` parameter
I'm getting an error `[Client 0] No match found for service, cancelling service call...`

### PR DESCRIPTION
**Pull request by Behery**
Also refactors the way the parameters are obtained. Fixes #291

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
The Python changes look good.  I like the refactor: one local function is much easier to reason about and maintain than three list comprehensions. It's also good that this only strips array brackets rather than truncating the first and last character and implicitly assuming array brackets are present.

There's a part of me that wants to find a way to perform these string manipulations all in one pass using a regular expression capture but  that's an indulgence worth ignoring unless this actually becomes a performance problem.

There are no tests for this project but can you provide a minimal example that is broken with the latest release and fixed by this PR?

Thanks!

**Comment by nuclearsandwich** [comment]
Oh, forgot to mention, the changes that this complements / fixes were introduced in https://github.com/RobotWebTools/rosbridge_suite/pull/252

**Comment by Behery** [comment]
Using the following launch file would cause it to break in the current release. The rosbridge_server will try to match service requests against 'o_something', and 'do_something_els' and will not be able to call the correct services.

```
<launch>
    <node name="my_ros_bridge_node" pkg="rosbridge_server" type="rosbridge_websocket.py" cwd="node" output="screen" respawn="true">
        <param name='services_glob' value='do_things, do_something_else'/>
    </node>
</launch>
```

**Comment by nuclearsandwich** [comment]
@jihoonl do we have a merge strategy for pull requests beyond "merge when ready"? Is there anything I should do to merge this, like changelog updates or other notes?

**Comment by jihoonl** [comment]
Not really. As soon as you approve, feel free to merge. I am merging it.

**Comment by nuclearsandwich** [comment]
Great! Thanks Behery for the contribution 🌈

**Pull request merged**
