### PR TITLE
FieldTypeMismatchException error in python3

### PR DESCRIPTION
**Pull request by TeamATR**
type bool changed to boolean in python3

### CODE REVIEW

**Comment by mvollrath** [comment]
Does this work in Python 2?

How can we reproduce the original issue?

**Comment by TeamATR** [comment]
@mvollrath 
I did not change anything which will affect while using Python2.
1. `type_map` is different due to the Python version.
2. `ros_primitive_types` is used for both Python versions, so I added `boolean` for Python 3 instead of changing `bool` to `boolean` so might affect Python 2.
3. Probably, should define a different `ros_primitive_types` according to the Python version which uses `boolean` just like `type_map`.

To reproduce the original issue, without changes, using Python 3, call `std_srvs/srv/SetBool` type service and pass data `{"data": True}`, will cause FieldTypeMismatchException.
e.g.
```python
service = roslibpy.Service(client, '/set_ludicrous_speed', 'std_srvs/srv/SetBool')
request = roslibpy.ServiceRequest({"data": True})
result = service.call(request)
```

**Comment by mvollrath** [comment]
I can't reproduce this issue in melodic, maybe there is some other environmental condition I'm missing?

**Comment by TeamATR** [comment]
I am sorry. I forgot to mention. I used it for ROS2-dashing env

**Comment by jihoonl** [comment]
I can't find any information that saying python3 uses boolean instead of bool. Would you provide where you found the change?

**Comment by TeamATR** [comment]
@jihoonl  @mvollrath Apologize! It is not because of Python version. It is the class `std_srvs.srv._set_bool.py` in my environment using defines `boolean` instead of using`bool`. 

In this case, where should I report the problem? Or it is just my local multiple libs compatibility problem?

**Comment by jihoonl** [comment]
There is `ros2` branch which you may be interested in. Would you try ros2 branch?

**Comment by TeamATR** [comment]
Thank you! Sure! I will close this pull request,  make a pull request to `ros2` branch.

**Pull request closed without merging**
