### PR TITLE
[ROS2] port package to ament_cmake, other necessary updates

### PR DESCRIPTION
**Pull request by dirk-thomas**
Related to #345.

* Port the packages from `catkin` to `ament_cmake`
* Use package names to reference builtin types / header
* Rename the fields which collide with keywords
* Add migration rules for the changed field names

**This PR is still in progress and shouldn't be merged yet.**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@jihoonl Can you grant a colleague of mine the same access as me for this repository? @jubeira has already worked on porting packages in ros2/rosbridge_suite#2 (and we would only use it for the `ros2` branch - not touching `develop` / `master`). Giving him write access to this repo would make it easier to rebase the `ros2` branch and iterate faster without relying on me to do so.

**Comment by jihoonl** [comment]
ok. Invitation is sent to @jubeira

**Comment by jubeira** [comment]
@dirk-thomas can we merge this branch to `ros2` and keep working against that branch? I can do the squash + merge and I'd suggest doing so.

**Comment by dirk-thomas** [comment]
> can we merge this branch to ros2 and keep working against that branch? I can do the squash + merge and I'd suggest doing so.

Sounds good to me. Maybe fast forward the `ros2` branch with the latest development before?

**Comment by jubeira** [comment]
Done; `ros2` branch is now in sync with `master`, and these changes were applied on top of it.
Thanks!

**Pull request merged**
