### PR TITLE
Build Tornado speedups

### LINKED ISSUE #135: Slow web socket performance
The rosbridge web socket server is very CPU hungry when a lot of messages are being routed to browser clients.

Our use case is subscription to multiple sensors from multiple browser clients for distributed, interactive visuals.  ROS is a great platform for this kind of thing, but when we ran rosbridge on a modest server (some kind of Atom processor with plenty of RAM), it couldn't keep up.  The server would eat a lot of CPU as message traffic ramped up, and sometimes choked up resulting in apparent system breakdown.  We ended up offloading the rosbridge server to a more powerful server, but we'd like for rosbridge to be efficient enough to handle hundreds of messages per second without burning up CPU cycles on a user-facing machine.

I looked around and found this discussion pointing at Tornado's web socket masking function as the culprit, with native speedups making an order of magnitude difference:

https://groups.google.com/forum/#!topic/python-tornado/n6VpUr8zk2c

Then this Tornado pull request to add native speedups:

https://github.com/tornadoweb/tornado/pull/579

Looks like it was released in Tornado 3.2.  Ubuntu's python-tornado package is still at 3.1.1 in trusty, but pip will install 4.0.2 as of today.  Presently rosbridge includes Tornado 2.3.

This is related to #121 which should resolve this issue if Tornado comes from pip or is updated to 3.2+ in the rosbridge tree.

Thanks
mv

### PR DESCRIPTION
**Pull request by mvollrath**
Copy fail-over build_ext code from Tornado's setup.py.

Fixes #135

### CODE REVIEW

**Comment by mvollrath** [comment]
I'll be happy to copy this into rosbridge_tools when it's ready.

**Comment by jihoonl** [comment]
Thanks @mvollrath. I will review the module this week and merge it.

**Comment by jihoonl** [comment]
I got the following error while catkin_make install process. I have confirmed that build-essential and python-dev were installed in my pc. Can you check what it is?

```
copying src/tornado/platform/kqueue.py -> /home/jihoonl/research/ros/isolate/build/rosbridge_suite/rosbridge_server/lib.linux-x86_64-2.7/tornado/platform
running build_ext
building 'tornado.speedups' extension
creating /home/jihoonl/research/ros/isolate/build/rosbridge_suite/rosbridge_server/temp.linux-x86_64-2.7
creating /home/jihoonl/research/ros/isolate/build/rosbridge_suite/rosbridge_server/temp.linux-x86_64-2.7/tornado
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c tornado/speedups.c -o /home/jihoonl/research/ros/isolate/build/rosbridge_suite/rosbridge_server/temp.linux-x86_64-2.7/tornado/speedups.o
x86_64-linux-gnu-gcc: error: tornado/speedups.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
/home/jihoonl/research/ros/isolate/src/rosbridge_suite/rosbridge_server/setup.py:72: UserWarning: 
********************************************************************
WARNING: The tornado.speedups extension module could not
be compiled. No C extensions are essential for Tornado to run,
although they do result in significant speed improvements for
websockets.
The output above this warning shows how the compilation failed.

Here are some hints for popular operating systems:

If you are seeing this message on Linux you probably need to
install GCC and/or the Python development package for your
version of Python.

Debian and Ubuntu users should issue the following command:

    $ sudo apt-get install build-essential python-dev

RedHat, CentOS, and Fedora users should issue the following command:

    $ sudo yum install gcc python-devel
********************************************************************

  "The output above "
command 'x86_64-linux-gnu-gcc' failed with exit status 4
running install
running install_lib
running install_egg_info
```

**Comment by mvollrath** [comment]
Thanks, working on it now.

**Comment by mvollrath** [comment]
Via 16445188a0f9f1fc8aeaac2576bbd43a5a05f395 I can now run catkin_make install without this warning.

**Comment by mvollrath** [comment]
To verify import I've prepended install/lib/python2.7/dist-packages to PYTHONPATH and imported tornado.speedups without exception.  Anything else I should be checking?

**Comment by mvollrath** [comment]
Advertise, subscribe and publish over ws all working for me.

**Comment by jihoonl** [comment]
:+1: Thanks @mvollrath. It compiles and works without any error for me too. :)

**Comment by mvollrath** [comment]
@jihoonl I am just now realizing that this change makes the packages specific to the build farm's arch.  At best, trying to use rosbridge_server after this patch in non-64bit env will fail to import the speedups silently (assuming it raises ImportError).  At worst, it will fail to launch.

There are probably some ways to work around this, but being able to use the system Tornado via those rosbridge_tools changes would suffice for my performance needs and be a better global solution than this PR imo.

**Comment by rctoris** [comment]
@mvollrath won't the build farms arch match the arch of the client downloading it always? This should be the expected behavior from pre-built binaries.

**Comment by jihoonl** [comment]
The build farm succeeded to build the new version of rosbridge_server.

http://www.ros.org/debbuild/indigo.html?q=rosbridge

**Comment by mvollrath** [comment]
Cool, I just assumed the debs are architecture: any/all for some reason.  Carry on :+1:

**Pull request merged**
