### PR TITLE
Release 0.11.5

### PR DESCRIPTION
**Pull request by mvollrath**

### CODE REVIEW

**Comment by jihoonl** [comment]
:+1: I will trigger release this weekend

**Comment by jihoonl** [comment]
FYI @mvollrath , I just gave you the full admin access  of RWT. Thanks for maintaining packages these days.

I plan to release on noetic as [rosauth](https://github.com/RobotWebTools/rosbridge_suite/pull/480) gets released.

**Comment by mvollrath** [comment]
Thank you @jihoonl

**Comment by hikinggrass** [comment]
@jihoonl given that [rosauth has been released for noetic](https://github.com/GT-RAIL/rosauth/issues/30), how's the status of the rosbridge_suite noetic release? Thanks a lot in advance!

**Comment by jihoonl** [comment]
Done. I just triggered the release process of version 0.11.8 rosbridge in noetic

https://github.com/ros/rosdistro/pull/25114

**Comment by mvollrath** [comment]
Tests are failing on noetic so 0.11.8 might be broken.  CI is not running noetic tests presently.

**Comment by mvollrath** [comment]
Service advertisement might be broken in 0.11.8 on noetic.

**Comment by mvollrath** [comment]
Also @jihoonl please upgrade your `bloom` before releasing, the old version breaks package dependencies since we changed to package format 3.  I will make an 0.11.9 to fix all this.

**Comment by mvollrath** [comment]
I bloomed 0.11.9 for kinetic and melodic but not noetic since it made bloom freak out.

**Comment by jihoonl** [comment]
ah ok. thanks for the info.

**Comment by hikinggrass** [comment]
Is there anything I can do to help with the noetic release? @mvollrath what exactly made bloom freak out for noetic that did not apply to kinetic/melodic?

**Comment by mvollrath** [comment]
I ran it again to get the error and it worked, must have been a typo :D  https://github.com/ros/rosdistro/pull/25189

**Pull request merged**
