### PR TITLE
Fix length-limited list types

### LINKED ISSUE #821: AttributeError: 'float' object has no attribute 'get_fields_and_field_types'
**Description**

Publishing shape_msgs/msg/SolidPrimitive messages through the rosbridge websocket (subscribing with roslibjs) gives a `'float' object has no attribute 'get_fields_and_field_types'`.

The error is on the dimensions attribute of the SolidPrimitive, a list of float64, but I can't understand why.

- Library Version: Installed with apt: ros-humble-rosbridge-server (1.3.0-1jammy.20220909.012557)
- ROS Version: ROS2 Humble
- Platform / OS: Ubuntu 20.04

**Steps To Reproduce**

1 -  Launch `ros2 launch rosbridge_server rosbridge_websocket_launch.xml`
2 - Publish `ros2 topic pub -r 1 /test shape_msgs/msg/SolidPrimitive "{type: 1, dimensions: {0.0, 1.0, 2.0}}"`
3 - Subscribe using roslibjs

**Expected Behavior**

Being able to subscribe the message.

**Actual Behavior**

This error on every message received:
```
[rosbridge_websocket-1] Traceback (most recent call last):
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/subscription_modifiers.py", line 161, in run
[rosbridge_websocket-1]     MessageHandler.handle_message(self, msg)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/subscription_modifiers.py", line 73, in handle_message
[rosbridge_websocket-1]     self.publish(msg)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/capabilities/subscribe.py", line 164, in _publish
[rosbridge_websocket-1]     self.publish(message, self.fragment_size, self.compression)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/capabilities/subscribe.py", line 372, in publish
[rosbridge_websocket-1]     outgoing_msg["msg"] = message.get_json_values()
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/outgoing_message.py", line 21, in get_json_values
[rosbridge_websocket-1]     self._json_values = extract_json_values(self._message)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 169, in extract_values
[rosbridge_websocket-1]     return _from_inst(inst, rostype)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 233, in _from_inst
[rosbridge_websocket-1]     return _from_object_inst(inst, rostype)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 268, in _from_object_inst
[rosbridge_websocket-1]     msg[field_name] = _from_inst(field_inst, field_rostype)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 230, in _from_inst
[rosbridge_websocket-1]     return _from_list_inst(inst, rostype)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 259, in _from_list_inst
[rosbridge_websocket-1]     return [_from_inst(x, rostype) for x in inst]
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 259, in <listcomp>
[rosbridge_websocket-1]     return [_from_inst(x, rostype) for x in inst]
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 233, in _from_inst
[rosbridge_websocket-1]     return _from_object_inst(inst, rostype)
[rosbridge_websocket-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosbridge_library/internal/message_conversion.py", line 266, in _from_object_inst
[rosbridge_websocket-1]     for field_name, field_rostype in inst.get_fields_and_field_types().items():
[rosbridge_websocket-1] AttributeError: 'float' object has no attribute 'get_fields_and_field_types'
```

### LINKED ISSUE #910: 'float' object has no attribute 'get_fields_and_field_types'
**Description**
When calling the `/get_planning_scene` service (moveit_msgs/srv/GetPlanningScene) it fails to serialize the results with the followign error:

`[rosbridge_websocket-1] [ERROR 1709106045.616655214] [rosbridge_websocket]: [Client 8b631744-1ef3-4af3-8555-3e8281b42001] [id: call_service:/get_planning_scene:8] call_service AttributeError: 'float' object has no attribute 'get_fields_and_field_types' (() at :0)`

Just to mention this PR fix the issue: [#840](https://github.com/RobotWebTools/rosbridge_suite/pull/840).

- Library Version: Build from source (7d78af16d30d0ffe232abcc65d0928ce90bd61f7)
- ROS Version: Humble
- Platform / OS: 22.04

**Steps To Reproduce**
I've seen others to have this error with different messages, but using moveit it is easy to make it fail, Just call the service get_planning_scene

### PR DESCRIPTION
**Pull request by EzraBrooks**
**Public API Changes**

None

**Description**

Removes the `, N` length specifier at the end of list types like `sequence<type, length>`. Fixes issues with serializing `shape_msgs/Polygon`, which has a `float64[<=3]` field.

Fixes #910

### CODE REVIEW

**Comment by EzraBrooks** [comment]
@achim-k can I get a review? this is a pretty brutal issue - it prevents serializing Polygons, which many planning- and geometry-related messages include.

**Review by achim-k — COMMENTED** [review]
I'm unfamiliar with the code path this PR touches but it looks correct. Could you add a unit test for this?

**Comment by achim-k** [comment]
@EzraBrooks #827 looks like it does the same / something similar. Can you check that one?

**Comment by JensVanhooydonck** [comment]
Got to the same solution. This solution seems ready to merge.

**Comment by sea-bass** [comment]
@achim-k The other PR (#827) has been closed and this one is tested and ready to merge. Can we merge this one in?

**Comment by EzraBrooks** [comment]
Closing in favor of #883, which fixes this particular issue and others.

**Comment by EzraBrooks** [comment]
Turns out this is still needed!

**Comment by EzraBrooks** [comment]
or at the least, my team is still running into an issue when serializing moveit planning scenes as described in #910. will dig a bit deeper, but this PR definitely fixes it

**Review by sea-bass — APPROVED** [review]

**Comment by sea-bass** [comment]
@EzraBrooks I was just looking through PRs to this repo and noticed this was still hanging around. Is this good to merge now? Will let you go ahead if so.

**Pull request merged**
