### PR TITLE
Fixes error when sending binary data

### PR DESCRIPTION
**Pull request by fran6co**
uint8[] is no necessarily a string, raw data like images is normally sent as uint8[]

For example I get this eror when sending images
```
call_service UnicodeDecodeError: 'ascii' codec can't decode byte 0x8a in position 2: ordinal not in range(128)
```

### CODE REVIEW

**Comment by tapan-d** [comment]
Works for me for Melodic(built from source to use python3) and Python3 along with [https://github.com/RobotWebTools/rosbridge_suite/pull/545] :+1:  Please approve and merge.

**Comment by amacneil** [comment]
We have recently fixed the CI on `ros1` branch, would you mind rebasing this PR?

**Comment by fran6co** [comment]
rebased, sorry it took this long

**Comment by amacneil** [comment]
Hello! Can you please take a look at why this is failing on noetic?

**Comment by amacneil** [comment]
@fran6co we can merge this once the noetic tests are passing in CI

**Comment by jamestiotio** [comment]
Hello! Can I check on when this PR will be merged? Seems like the CI logs have expired. Thanks!

**Comment by amacneil** [comment]
I just tried rebasing, but there is still a failing unit test on noetic. I don't know this codebase so I can't speak to why it's failing, but we can't merge a PR that breaks the tests.

**Comment by jamestiotio** [comment]
Hmm after digging around, the code line involved in this PR seems to have been changed in a [past commit](https://github.com/RobotWebTools/rosbridge_suite/pull/593/files#diff-212be7c9fa67fbb1f8af9069876e393724e387108a685d2cc0a2f2375b561ddbL175-R164).

I am not sure which option would be the correct one to support sending binary data through rosbridge.

**Pull request closed without merging**
