### PR TITLE
Adaptations to Eloquent [Again]

### PR DESCRIPTION
**Pull request by travipross**
This is an extension to #493 which fixes some outstanding requests from code review, and adds some extra fixes.

### CODE REVIEW

**Comment by travipross** [comment]
This PR should replace #493 and #531 if accepted.

**Comment by flynneva** [comment]
bright side of all of these ROS2 PR's is that the github actions seem to be working :smile:

**Comment by travipross** [comment]
> bright side of all of these ROS2 PR's is that the github actions seem to be working

Yes! Very happy to see the green checkmarks again.

**Review by mvollrath — APPROVED** [review]

**Comment by AviKenz** [comment]
Very Happy to see this. 😃😃😃
Thanks @travipross and @mvollrath.
I will check if [THIS](https://github.com/RobotWebTools/rosbridge_suite/issues/530) is gone and let you know.
Many Thanks again !!! :)

**Pull request merged**
