### PR TITLE
Revert import rospy

### PR DESCRIPTION
**Pull request by cclauss**
As discussed at https://github.com/RobotWebTools/rosbridge_suite/pull/593#pullrequestreview-734308510

### CODE REVIEW

**Comment by cclauss** [comment]
@jtbandes @amacneil Your reviews, please.

**Review by jtbandes — APPROVED** [review]
Thanks. FYI the code that would have triggered the NameError is commented out: 

https://github.com/RobotWebTools/rosbridge_suite/blob/cfe65e203806f83e9f6a43d25acc5f85590508be/rosapi/scripts/rosapi_node#L89-L91

**Comment by cclauss** [comment]
A new _undefined name_ after this revert...
```
./rosapi/src/rosapi/params.py:240:12: F821 undefined name 'rospy'
    return rospy.search_param(name)
           ^
```

**Comment by jtbandes** [comment]
Yep, that is currently disabled code. I suppose we can comment out this line since it will never work in ROS 2 anyway.

**Pull request merged**
