### PR TITLE
Fixed namespacing services

### PR DESCRIPTION
**Pull request by reinzor**
Pull request suggestion for issue https://github.com/RobotWebTools/roslibjs/issues/173

### CODE REVIEW

**Comment by rctoris** [comment]
Looks like some tests are failing. 

If the service name is absolute (e.g., `/my_service`) I don't think anything needs to be appended otherwise you will get `//my_service`.

**Comment by reinzor** [comment]
Added fix for this in commit 26493ac72a2089f5747f554cf1a888733df8625d

**Comment by rctoris** [comment]
@jihoonl Does this look reasonable?

**Comment by jihoonl** [comment]
It seems to support to call service in rosbridge local namespace. Would it work if for absolute namespaced service?

I think it should check leading slash of `service`  argument, then add namespace only if there is no leading slash. 

For example,  rosbridge is running under `my_namespace`. and user wants to call `/hello/world` service. The current logic would search for `/my_namespace/hello/world`

**Comment by Rayman** [comment]
I updated the PR, it now uses the `rospy.resolve_name` function so the logic isn't duplicated. The test suit still runs but maybe we should add some extra tests to it for relative services/topics.

**Comment by jihoonl** [comment]
I think this is right approach to resolve the issue.

@rctoris,  two questions.
1. do you think this approach should be applied to subscriber and publisher too?
2. I think This patch might break many client applications as I assume many users would have used to call global namespaced ros services without leading slash. Where would be nice place to warn or inform users about this change?

**Comment by jihoonl** [comment]
After some testing, it seems fine. Merging.

**Comment by jihoonl** [comment]
Thank @Rayman, @reinzor

**Pull request merged**
