### PR TITLE
(actions) run rolling on ubuntu 22.04

### LINKED ISSUE #725: Broken CI
CI is broken because ROS2 rolling has migrated to Ubuntu 22.04 (Jammy). See https://github.com/ros/rosdistro/commit/0827daacdc5b4fc46d07e81bff448b2c909b8e9f

As Ubuntu 22.04 is not yet available for GH actions. The CI will stay broken until Ubuntu 22.04 is available.

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Fixes #725

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
CI error caused by https://github.com/ros2/launch/blob/84ab8bee0be4bdcdd2f4f4b742e7bd10752a92ef/launch_testing/launch_testing/test_runner.py#L273-L302

Someone more into ROS2, please do some research on this. Might be a result of python 3.8 vs 3.10.

**Comment by jtbandes** [comment]
`ready_fn` was removed in https://github.com/ros2/launch/pull/589. We need to use an alternate approach for Humble/Rolling.

**Comment by jtbandes** [comment]
I see some errors in the console, but ultimately things are passing:

```
3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1] Failed to publish log message to rosout: publisher's context is invalid, at ./src/rcl/publisher.c:389
[4992](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5003)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1] Traceback (most recent call last):
[4993](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5004)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]   File "/home/runner/work/rosbridge_suite/rosbridge_suite/ros_ws/install/rosbridge_server/lib/rosbridge_server/rosbridge_websocket", line 332, in <module>
[4994](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5005)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]     main()
[4995](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5006)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]   File "/home/runner/work/rosbridge_suite/rosbridge_suite/ros_ws/install/rosbridge_server/lib/rosbridge_server/rosbridge_websocket", line 327, in main
[4996](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5007)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]     rclpy.shutdown()
[4997](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5008)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]   File "/opt/ros/rolling/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 126, in shutdown
[4998](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5009)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]     _shutdown(context=context)
[4999](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5010)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]   File "/opt/ros/rolling/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
[5000](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5011)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]     return context.shutdown()
[5001](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5012)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]   File "/opt/ros/rolling/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
[5002](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5013)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1]     self.__context.shutdown()
[5003](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5014)
  3: 2022-05-23 18:35:51+0000 [-] [rosbridge_websocket-1] rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
[5004](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5015)
  Error: -05-23 18:35:52+0000 [-] [ERROR] [rosbridge_websocket-1]: process has died [pid 24266, exit code 1, cmd '/home/runner/work/rosbridge_suite/rosbridge_suite/ros_ws/install/rosbridge_server/lib/rosbridge_server/rosbridge_websocket --ros-args --params-file /tmp/launch_params_ddocqej6'].
[5005](https://github.com/RobotWebTools/rosbridge_suite/runs/6560941502?check_suite_focus=true#step:4:5016)
```

**Comment by jtbandes** [comment]
Humble still experiencing errors:

```

...
  ERROR: the following rosdeps failed to install
612
    apt: command [sudo -H apt-get install -y ros-humble-ament-cmake-core] failed
613
    apt: command [sudo -H apt-get install -y ros-humble-ament-cmake-ros] failed
614
    apt: command [sudo -H apt-get install -y ros-humble-rosidl-default-generators] failed
615
    apt: command [sudo -H apt-get install -y ros-humble-builtin-interfaces] failed
616
    apt: command [sudo -H apt-get install -y ros-humble-rcl-interfaces] failed
617
    apt: command [sudo -H apt-get install -y ros-humble-rosidl-default-runtime] failed
618
    apt: command [sudo -H apt-get install -y ros-humble-actionlib-msgs] failed
619
    apt: command [sudo -H apt-get install -y ros-humble-ament-cmake-pytest] failed
620
    apt: command [sudo -H apt-get install -y ros-humble-diagnostic-msgs] failed
621
    apt: command [sudo -H apt-get install -y ros-humble-example-interfaces] failed
622
    apt: command [sudo -H apt-get install -y ros-humble-geometry-msgs] failed
623
    apt: command [sudo -H apt-get install -y ros-humble-nav-msgs] failed
624
    apt: command [sudo -H apt-get install -y ros-humble-sensor-msgs] failed
625
    apt: command [sudo -H apt-get install -y ros-humble-std-msgs] failed
626
    apt: command [sudo -H apt-get install -y ros-humble-std-srvs] failed
627
    apt: command [sudo -H apt-get install -y ros-humble-stereo-msgs] failed
628
    apt: command [sudo -H apt-get install -y ros-humble-tf2-msgs] failed
629
    apt: command [sudo -H apt-get install -y ros-humble-trajectory-msgs] failed
630
    apt: command [sudo -H apt-get install -y ros-humble-visualization-msgs] failed
631
    apt: command [sudo -H apt-get install -y ros-humble-ament-cmake] failed
632
    apt: command [sudo -H apt-get install -y ros-humble-rclpy] failed
633
    apt: command [sudo -H apt-get install -y ros-humble-shape-msgs] failed
634
    apt: command [sudo -H apt-get install -y ros-humble-rmw-dds-common] failed
635
    apt: command [sudo -H apt-get install -y ros-humble-ros2node] failed
636
    apt: command [sudo -H apt-get install -y ros-humble-ros2param] failed
637
    apt: command [sudo -H apt-get install -y ros-humble-ros2pkg] failed
638
    apt: command [sudo -H apt-get install -y ros-humble-ros2service] failed
639
    apt: command [sudo -H apt-get install -y ros-humble-ros2topic] failed
640
    apt: command [sudo -H apt-get install -y ros-humble-launch] failed
641
    apt: command [sudo -H apt-get install -y ros-humble-launch-ros] failed
642
    apt: command [sudo -H apt-get install -y ros-humble-launch-testing] failed
643
    apt: command [sudo -H apt-get install -y ros-humble-launch-testing-ros] failed
644
    apt: command [sudo -H apt-get install -y ros-humble-launch-testing-ament-cmake] failed
645

...
    Could not find a package configuration file provided by "ament_cmake_ros"
739
    with any of the following names:
740
  
741
      ament_cmake_rosConfig.cmake
742
      ament_cmake_ros-config.cmake
743

```

**Review by jtbandes — APPROVED** [review]

**Pull request merged**
